### ISSUE TITLE
VST3 + DISTRHO_PLUGIN_HAS_EXTERNAL_UI view sizing

### ISSUE THREAD

**Issue by lucianoiam** [DISTRHO/DPF#359]
Excellent work on the VST3 implementation !

I inserted a debug message into DistrhoUIVST3.cpp like this:

```
    void doIdleStuff()
    {
        d_stdout("doIdleStuff()");

     ...
```

And noticed the message is never printed when `DISTRHO_PLUGIN_HAS_EXTERNAL_UI` is defined.

Is this the expected behavior?  specifically my plugins are failing to request a new size, while the VST2 builds work as expected. DPF prints this instead:

`plugin->host setSize 600 300 (IGNORED, host resize active)`

Looks like the flag `fIsResizingFromPlugin` is always true and never cleared because `doIdleStuff()` is never called. There is a single `fIsResizingFromPlugin = false` line and it belongs to that method. I think this flag prevents a resizing feedback loop but honestly I haven't thoroughly studied this.

**Comment by falkTX** [comment]
I didnt spend any time on vst3 and external ui yet, there is going to be a need to write some custom code to handle that properly on non-x11 platforms.
I would say the vst3 ui is not ready yet, and focus should be on finalizing the non-external stuff first. At least right now on there are issues reopening the UI on bitwig.

Once the non-external stuff works fine, I will see about the external case.

But if you want to help out, the situation here is that vst3 does not expose ui idle time for win/mac, only on x11 (by the use of the host-timer interface).
On win/mac the way I got this to work is to register a callback with pugl that will drive the plugin UI, rather than the host calling ui idle and that driving the pugl stuff (which is how all other formats work in dpf).
For x11 though, it should work similar to vst2 in theory, so it will be easier to make that work first.

**Comment by lucianoiam** [comment]
Naive question but why VST3 cannot just work like VST2 in this regards? is there a fundamental difference, like VST2 requiring the host to call a method at a regular interval, and VST3 not?

I see `DPF_VST3_USING_HOST_RUN_LOOP` will only work for Linux but not sure why.

For Mac there is GCD or `NSTimer`. A further method optimized for graphics is called `CADisplayLink`. Just throwing in some names, maybe you already saw all this. Would need to better understand the stack myself.

Leaving some links found on the way
https://dmtopolog.com/cadisplaylink-and-its-applications/
https://stackoverflow.com/questions/55131532/difference-between-dispatchsourcetimer-timer-and-asyncafter

**Comment by falkTX** [comment]
> I see `DPF_VST3_USING_HOST_RUN_LOOP` will only work for Linux but not sure why.

It is just how it is defined in the spec.
Instead of hosts driving the plugin UI event loop, UIs are now supposed to hook into the native OS APIs instead.
Since Linux/X11 does not have such APIs, one is provided by the host.

**Comment by lucianoiam** [comment]
Thanks, makes sense. I'll start by having a look on macOS.

**Comment by lucianoiam** [comment]
Probably I'm insisting on something that is not supposed to work yet, but asking anyways. On REAPER/Linux, d_parameters displays fine but clicking on any of the boxes does not trigger an update on DSP's side (can be checked by switching to the generic plugin UI). The inverse works though, tweaking a param using generic UI is reflected when reopening the custom UI. Is this expected at this stage?

( BTW, UI input and graphics work as expected on Linux like pointed out in an earlier message )

Adding some new findings related to external UI, actually the tough part might not be such:

On Mac I realized my existing system widget-based UIs already work out of the box, there is no extra work needed to hook into the host main loop. This is apparently because inserting a native view into the host-provided parent native view already ensures the child will get events (comment no. 2 [here](https://www.kvraudio.com/forum/viewtopic.php?t=521566)). What is missing is calling the `doIdleStuff()` method periodically because it is required by some internal DPF operations. That's probably all. The sizing problem is not an issue with the native widgets themselves. 

Same is true for Windows, native widget works and even displays in the expected size. This is surprising but I would wait until trying live resizing.

Overall this looks promising.

**Comment by falkTX** [comment]
> Probably I'm insisting on something that is not supposed to work yet, but asking anyways. On REAPER/Linux, d_parameters displays fine but clicking on any of the boxes does not trigger an update on DSP's side (can be checked by switching to the generic plugin UI). The inverse works though, tweaking a param using generic UI is reflected when reopening the custom UI. Is this expected at this stage?

I thought I fixed that already, you sure you are using latest develop stuff?



> On Mac I realized my existing system widget-based UIs already work out of the box, there is no extra work needed to hook into the host main loop. This is apparently because inserting a native view into the host-provided parent native view already ensures the child will get events (comment no. 2 [here](https://www.kvraudio.com/forum/viewtopic.php?t=521566)). What is missing is calling the `doIdleStuff()` method periodically because it is required by some internal DPF operations

Yes, and that is exactly the problem.

On external UI the issue is not that directly noticeable but on native/embed it can make the UI simply not draw anything.
The external UI doesnt have that much work to do internally.

**Comment by lucianoiam** [comment]
Started clean and retested with same result, latest commit :/

Regarding the events part all clear, thanks for clarifying.

**Comment by falkTX** [comment]
Ok I need to check reaper again, all these damn hosts implement vst3 differently, it is frustrating..

**Comment by lucianoiam** [comment]
Added a PR that implements a native timer for calling `doIdleStuff()` on macOS.

This alone has not solved the size problem mentioned above. It seems to be rooted in the UI initialization, won't bother too much with external right now -- just trying to understand what is the purpose of the `willResizeFromHost` in `UIVst3` constructor coz I can't infer it from the name:

```
UIVst3(v3_plugin_view** const view,
           v3_host_application** const host,
           v3_connection_point** const connection,
           v3_plugin_frame** const frame,
           const intptr_t winId,
           const float scaleFactor,
           const double sampleRate,
           void* const instancePointer,
           const bool willResizeFromHost)
        : fView(view),
          fHostApplication(host),
          fConnection(connection),
          fFrame(frame),
          fReadyForPluginData(false),
          fScaleFactor(scaleFactor),
          fIsResizingFromPlugin(false),
          fIsResizingFromHost(willResizeFromHost),
          fUI(this, winId, sampleRate,
              editParameterCallback,
              setParameterCallback,
              setStateCallback,
              sendNoteCallback,
              setSizeCallback,
              nullptr, // TODO file request
              d_nextBundlePath,
              instancePointer,
              scaleFactor)
```

It is set to true when `view->nextWidth > 0 && view->nextHeight > 0`.  Under which circumstances nextWidth or nextHeight can be 0?

If I hardcode `willResizeFromHost` to false, my plugin size is the expected when opening the UI. Note this issue only affects Mac VST3, and not Linux or Windows. Same plugin codebase works as expected for VST2.

Pseudocode for UI subclass constructor:

```
super( someWidth, someHeight )   //  non zero dimensions

setSize( N * getWidth(), N * getHeight() )   //  does not work, DPF complains "(IGNORED, host resize active)" 
```

I guess the timer patch will fix the "IGNORED..." issue when trying to resize the plugin *after* initialization ( because `fIsResizingFromHost` is now regularly cleared ) but this has nothing to do with the init sequence just described above.

**Comment by falkTX** [comment]
The issue with vst3 resizing is that by spec it needs to work differently than anything before it.
Contrary to vst2, on vst3 only the host is allowed to change the size of the window, the plugin UI itself is not.
For the UI to set its own size, it needs to request a resize to the host, which will either then call the resizing methods or ignore the request.

The initial size (called "nextWidth" etc here in DPF) happens because sometimes hosts request the size of an UI before it is created. The host can set a custom size before UI is created too.
So in order to support this, dpf caches the "next width/height to use once a UI is created", and if that is not zero it gets set as the initial size of the plugin UI.
This behaviour differs between hosts, some will create the UI and then ask its size; some will ask the size and then create the UI.

Because of the weird way vst3 wants to handle UI resizing, dpf uses "resizing from host" and "resizing from plugin" flags to know the current state.

For example, if the host has just triggered a UI size change we need to ignore the plugin's setSize callback (because it was triggered due to a host initial event). This is the case for the first size request you are seeing on your logs, where it complains about the "host resize active". Since the host requested a size change, the plugin should not then at the same time request also a size change, to prevent recursion.

On the other side, after the UI is open and the plugin requests a size change, we need to flag that so that the next host-side resize event is handled properly, as a way to know that this size request originally initiated from the plugin side and is now being called by the host as specified by vst3.

It is a bit messy, but that is just how vst3 defines the size stuff.

**Comment by lucianoiam** [comment]
Thanks a lot for the detailed insight. What a powerful trademark VST is, cannot find a better explanation. 

Do you think clearing `fIsResizingFromHost` immediately after being tested in `setSize()` is safe? if I correctly understood it is enough with a skipping a single size request. It sounds cleaner than ignoring requests until a (IMHO) unrelated event happens in the future, that is the idle callback (though this can be complementary). Can you think of any side effects?

```
        if (fIsResizingFromHost)
        {
            fIsResizingFromHost = false;   // <-- new line
            d_stdout("plugin->host setSize %u %u (IGNORED, host resize active)", width, height);
            return;
        }
```

This allows doing things like shown in the pseudocode snippet above (tested: issue goes away for my plugin).

**Comment by falkTX** [comment]
> Do you think clearing `fIsResizingFromHost` immediately after being tested in `setSize()` is safe?

no, I dont think that is a good idea. a plugin doing 2 resize requests would have the 2nd one working but not the 1st, which is very inconsistent.

**Comment by lucianoiam** [comment]
I spent a while digging down the UI layers and think I won't be able to fix this on my own because it involves touching things I don't really understand :)

It is probably a special case after all; I fixed this by altering my plugin init in a way that is harmless to VST2 and LV2. 

Should I close this issue report or rename it?  there's the other issue with parameters on REAPER/Linux. Probably it deserves a new issue report?

**Comment by falkTX** [comment]
You can keep it open, I can try this again later on

**Comment by lucianoiam** [comment]
Cool, FYI made an interesting finding. I have a basic gain plugin which runs fine as VST3 on REAPER/Mac. Updating a parameter using the custom UI isn't reflected in REAPER's generic UI (as with d_parameters like described above) but... it actually has an effect on DSP! ie, gain control works sound-wise.  So it's more confusing now and yeah totally look like some REAPER specific thing.

**Comment by falkTX** [comment]
Huh I thought it was only for parameter outputs that things didnt get updated.
worth testing with and without instance access, dpf does the vst3 plugin a bit differently depending on that config

**Comment by lucianoiam** [comment]
Setting `DISTRHO_PLUGIN_WANT_DIRECT_ACCESS` to 1 fixes the issue !

BTW, my plugin relies on some functions in DistrhoUtils.cpp but enabling direct access renders such methods unavailable, have a look at DistrhoUIMain.cpp:

```
#if !DISTRHO_PLUGIN_WANT_DIRECT_ACCESS && !DISTRHO_PLUGIN_TARGET_JACK && !DISTRHO_PLUGIN_TARGET_VST2 && !DISTRHO_PLUGIN_TARGET_VST3
# ifdef DISTRHO_PLUGIN_TARGET_DSSI
#  define DISTRHO_IS_STANDALONE 1
# else
#  define DISTRHO_IS_STANDALONE 0
# endif
# include "src/DistrhoUtils.cpp"
#endif
```

Removing `DISTRHO_PLUGIN_WANT_DIRECT_ACCESS` from the preprocessor conditional allows DistrhoUtils.cpp to be included and my plugin to compile. But not sure there are side effects, what should be do here?

**Comment by falkTX** [comment]
I think you misunderstand. the direct access means the same object is used for dsp and ui, so it only needs to be defined on dsp side (otherwise the function symbol is duplicated)

**Comment by lucianoiam** [comment]
That's true, I think I found the source of confusion. I took d_info this time to rule out any issues in custom code. There is a combination that makes compilation fail, which is:

- Add `getBinaryFilename()` call in UI code.
- Add `#define DISTRHO_PLUGIN_WANT_DIRECT_ACCESS 1`
- Leave `TARGETS += lv2_sep`

Result:

```
Creating LV2 plugin UI for d_info
Undefined symbols for architecture x86_64:
  "DISTRHO::getBinaryFilename()", referenced from:
      DISTRHO::InfoExampleUI::InfoExampleUI() in InfoExampleUI.cpp.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [../../bin/d_info.lv2/d_info_ui.dylib] Error 1
make: *** [examples] Error 2
```

If I correctly understand lv2_sep produces two separate binaries so the utils code is missing for the UI *only for this special case*

Summarizing, the current workaround for VST3 on REAPER is enabling DISTRHO_PLUGIN_WANT_DIRECT_ACCESS. And for any plugins hitting the unique configuration above, either lv2_sep needs to be disabled or calls to util removed from UI.

**Comment by falkTX** [comment]
you cant have lv2 dsp+ui instance access if the dsp and ui binary objects are in different files.
so that is not an issue, and not meant to happen at all. we can ignore it.

the issue in reaper might be due to dpf then separating component from controller (in vst3 terms).
vst3 has this whole logic about such separation, which I went to great lengths to ensure it works for dpf. but sadly very very very few plugins actually do this separation, really I think it is single digits.
so might just be no bug at all on our side, dont know yet.
one thing that is not working for sure: parameter outputs (read-only in vst3 terms) do not get updated on the host internal editor. I confirmed this to be a bug in ALL vst3 hosts when the plugin does not have a custom gui.
hosts were simply not expecting plugins to not ship with a custom gui ?? anyway, bitwig at least confirmed the issue and said fix coming.

**Comment by lucianoiam** [comment]
You're right, I focused too much in a single thing and forgot the fact that direct access does not make sense if you are planning to support lv2_sep. It might be interesting to detect this invalid configuration and throw a compilation time error, though.

And having direct access for a format and not having it for another just does not make sense. This was only a test for VST3 and got overly enthusiastic about it lol.

Thinking twice, if DSP gets updated on UI changes that's enough for claiming VST3 compatibility. Though I don't know the internals I better get the situation now and there's not much to do other than wait for the DAW makers. Thanks for the insights, I find this really unbelievable.

**Comment by falkTX** [comment]
well I said it before: vst3 has some great ideas, but some really awful ones too.
the more complex something becomes, the harder it is to implement, so I think it is quite natural that a few edge-cases slip through.
specially coming from vst2 where dsp and ui/controller couldnt be separated.

**Comment by lucianoiam** [comment]
This should be addressed by a consortium of DAW makers, really cannot understand how they are allowing a company that is not that relevant anymore to take over this opportunity and let them continue profiting on some old trademark, at the expense of development resources. I'm quite sure the DAW guys would rather spend that money on new features for their products. I see a single winner in this scenario. /r

**Comment by falkTX** [comment]
well the alternative is LV2, or making yet another standard.
bitwig and u-he are pushing for the latter, due to one of their developers having a hate for LV2 and the project managers just going with it instead of finding out by themselves if there is actually useful stuff in LV2 or not... :disappointed: 

JUCE indicated in https://github.com/juce-framework/JUCE/issues/123#issuecomment-1008798161 that LV2 support is in the final stages, so let's hope the audio industry is more welcoming to LV2 than bitwig is.
We dont need yet another standard, there are too many of them already.

**Comment by lucianoiam** [comment]
Well a consortium does not necessarily need to develop a new standard, I was thinking about LV2 as well. The key point is that no private single company should be allowed to leverage the lack of coordination in the industry, this is already proven: many decades of no-coordination + VST2 led us to VST3. As a DAW maker now you are forced to adopt it... It is not free. And users? well, users couldn't care about less. Nonetheless great commercial move by SB.

Bitwig supporting Linux and not LV2 is mesmerizing. Also supporting JACK but not JACK-MIDI. Not sure how could I trust them to push for a new "open" standard this way. IMHO one should try to make friends first. Otherwise all we will have is a new AAX and I don't think Bitwig has such a leverage to push that. Hope they reconsider this, solving a coordination problem cannot be done by engineering only. 

I found your contributions to JUCE/LV2 in the past but didn't follow the saga, so great they will be finally adopting it!  It's actually a HUGE move for the format! well done.

**Comment by falkTX** [comment]
We can always try to coordinate something with David Robilla, author and current maintainer of LV2.
He knows about the whole situation and issues, there is a whole work around "lv2kit" being done behind the scenes just to make LV2 more palatable to those used to those sorta all-in-one SDKs.
afaik even pugl will be contained in it eventually.

> I found your contributions to JUCE/LV2 in the past but didn't follow the saga, so great they will be finally adopting it! It's actually a HUGE move for the format! well done.

To be clear here, they are using 0% of my code. Everything on the LV2 implementation they did is from scratch.
They are not interested on outside collaborators at all.

**Comment by lucianoiam** [comment]
Definitely great to have some all-in-one solution. I personally prefer to pick smaller tools and group them together but the fact why (for example) JUCE is so popular shouldn't be overlooked.

I recall reading something about the collaboration thing, go figure.

Off topic but still related to formats. What is the state of the AU branch? I'm sadly having little time for open source lately but still hoping to contribute, I have some experience on AU.

**Comment by falkTX** [comment]
the AU stuff kinda got stuck because I lost motivation for it.
for AU we need to keep in mind if we want to do the older, more generally supported but deprecated AUv2 or the new AUv3 format.
the initial work was done for AUv2

something else to keep in mind is that newer macOS (anything since 10.14 or something) cache the AU plugin information and does not invalidate it even after replacing their component files.
also AU plugins require a special non-trivial step of generating a "*.r" resource file using tools native to macOS (making cross-compilation difficult)
those were the step that pushed me away, it was too much of a hassle to test things.

by now devs probably figured out ways around them. I remember @jpcima having some opensource tool to generate the resource files

**Comment by lucianoiam** [comment]
Excellent, thanks very much for the overview.

**Comment by jpcima** [comment]
> also AU plugins require a special non-trivial step of generating a "*.r" resource file using tools native to macOS

This is still in use nowadays? the code is here if you need it. https://github.com/jpcima/AuRez
It took most of the resource format reference from an old book on Mac OS 9 internals.

**Comment by lucianoiam** [comment]
This issue was fixed in https://github.com/DISTRHO/DPF/commit/4313bac8873d9f62c9a6319a4a8faba8219147e2
