### ISSUE TITLE
External/embedded UI takes lots of CPU in suil's x11_in_gtk2

### ISSUE THREAD

**Issue by pdesaulniers** [DISTRHO/DPF#88]
If I run Zyn with the NTK UI in jalv.gtk, I get huge CPU usage (htop says 80% for jalv). That's in part due to this function: 

https://github.com/drobilla/suil/blob/master/src/x11_in_gtk2.c#L58

My understanding is that DPF external/embedded UIs set the LV2 UI widget ID to 0. So, this condition is always false: 
```c
if (children[i] == (Window)socket->instance->ui_widget) {
```

It causes suil to constantly queue resizes requests:

https://github.com/drobilla/suil/blob/9a93d3c3b9ffe7ff7fe2602d0523d4f80655e8aa/src/x11_in_gtk2.c#L234

If I comment out that g_idle_add call, CPU usage is low.

Anyway, I don't know what I'm supposed to do to fix this, or if this is even a DPF bug at all. Any clues? 

(well, I guess avoiding external UI would be the best thing to do :stuck_out_tongue:)

**Comment by falkTX** [comment]
external UI will not call gtk2 stuff.

we had a similar issue, but I believe it got fixed in latest git.
is your lv2 stack updated, including suil? what about jalv?

on X11 UI, the widget is set correctly.

**Comment by pdesaulniers** [comment]
> external UI will not call gtk2 stuff.

Does that mean I should be using `jalv -s` instead of `jalv.gtk` ? I get a segfault in DISTRHO::lv2_instantiate when doing so. I can investigate this further if this is relevant.

> is your lv2 stack updated, including suil? what about jalv?

AFAIK, yes. I've just built the following packages that pull from latest git, and still get the issue: `lilv-git lv2-git jalv-git suil-git serd-git sord-git sratom-git`

BTW, is there any reason why external UIs in DPF don't use the KXStudio LV2 extension? (http://kxstudio.sf.net/ns/lv2ext/external-ui#Widget) There doesn't seem to be anything special in the ttl telling the host that it's dealing with an external UI.

**Comment by falkTX** [comment]
there is no reason to add complications of external/non-external ui since we always have a native window handle. the code is a lot simpler when using the native window type and allow to show/hide via lv2 show interface.
For kx external-ui widget, we need to support ui side features and handle the detection properly. the host might be using:
1. native window type, embed as usual
2. native window type, but with show interface
3. kx external-ui type

I did this for carla-as-plugin UI, and it gets quite messy. so I leave support for kx external-ui out, to simplify the codebase.
It is not an official extension, and it was done before we had show interface.
Nowadays that extension is a bit pointless. Not to mention confusing to new developers.

For the Zyn NTK UI issue, we could fix it by waiting for NTK UI to start and have it communicate its window ID before returning from ui instantiate, so we can pass that ID to the host.
but well, considering NTK is barely used nowadays and Zyn has a proper embed UI now, I do not think pursuing this is worth the effort.

**Comment by falkTX** [comment]
I think this needs to be patched in suil.
But I do not want to close this bug. I will try to reproduce it, and do a patch-fix for suil

**Comment by falkTX** [comment]
Note to readers: suil-gtk is getting some patches to handle min size and aspect ratio, which involves changing the core resize code.
Might be that we get this fixed for free.

**Comment by falkTX** [comment]
I am postponing this bug to long-term, as LV2 stack is going to change quite drastically soon, and I rather wait for that and recheck what is the current status.

**Comment by falkTX** [comment]
I am going over tickets in DPF, and will close this one.
It is not actually an issue with DPF, but in suil.
